### ISSUE TITLE
Query about BhattMethod

### ISSUE THREAD

**Issue by lonelyjoeparker** [jnarag/teaspoon#15]
@jnarag in BhattMethod.inferCountsFixedNR() (line:1015 as of 14f17a2) labels `finalmat[3][i]` as silent/replacement ratio .. but that seems inverted as later it is assigned to `replacementSilentRatesRatio`?

```
double[] temp = calculateSiteFrequenciesWithinInterval(binsvalues[0][i], binsvalues[1][i],prior,needPrior);
finalmat[0][i] = temp[0];   // number silentProb, sigma
finalmat[1][i] = temp[1];	// number replacement, rho

totals[0][i] = temp[2];		// total count
totals[1][i] = temp[3];		// total variant
totals[2][i] = temp[4];		// total invariant
if(temp[1]!=0){      // was temp[1] but should be temp[0]
                finalmat[3][i] = temp[1]/temp[0];	// Silent/replacement ratio
} else {
                finalmat[3][i] = Double.NaN;
}
```
I double checked calcsiteFreqsWithingInterval(), and it definitely returns temp[0] temp[1] as sigma; rho, respectively... am I missing something or is the comment in line 1015 just plain wrong??

**Comment by jnarag** [comment]
Hi Joe, 

Line 1015 is definitely  a typo - elsewhere (for a similar method) it states “replacement/silent ratio”. Sorry for the confusion! 

Jayna

**Comment by lonelyjoeparker** [comment]
No worries, cheers for clearing that up. Also: just below we have
```
        int flag=0;
        for(int i=0;i< (int) numBins;i++){
            if(whichBins[i]==false && flag==0){
                this.deleteriousLoad+=getNonNeutralSubstitutions()[i];
            }
            if(whichBins[i]){flag=1;}
            if(whichBins[i]==false && flag==1){
                this.adaptation+=getNonNeutralSubstitutions()[i];
            }
        }
```
... We only ever seem to pass `whichBins ={false,false,false}`, and I can't find any other references/accesses to `BhattMethod.adaptation` or `BhattMethod.deleteriousLoad` either. Is this just a remnant of something never shipped/implemented, or is it needed?

**Comment by jnarag** [comment]
I think this was from one of Samir’s thesis chapters. The basic idea is that we can look at non-neutral changes in the low-freq class, which here are assumed to deleterious (while in the high-freq class we assume non-neutral changes are adaptive). 

It doesn’t need to be included in the main teaspoon framework, and in theory if folks are interested in this problem they could work this out from the output files (e.g. the neutral ratio and the silent and replacement polymorphisms in the low-free class).

**Comment by lonelyjoeparker** [comment]
OK that makes sense. Think I'll drop it from the new class then - apart from anything else, I couldn't see how BhattMethod.adaptation was ever going to get written to if Nvec elements are always negative...
