### ISSUE TITLE
Clarify allowed ranges (Infinity and/or NaN) for estimated neutral rate

### ISSUE THREAD

**Issue by lonelyjoeparker** [jnarag/teaspoon#17]
In `teaspoon.adaptation.BhattMethod.inferCountsEstimatedNR()` it is possible to get inifinity or NaN values back - is this allowed / how should it be handled. 

e.g. `BhattMethod.inferCountsEstimatedNR()` [line 1024]:
```
        // calcualate neutral ratio. Vector NeutralVec provides boolean true false if a given bin is neutral
        // user has to specify this bin
        double counter = 0;
        double NR=0;
        for(int i=0;i<(int) numBins;i++){
            if(whichBins[i]){
            	// check silent prob for this bin
                if(finalmat[0][i]!=0){
                	// replacement number / silent prob
                    NR += finalmat[1][i]/finalmat[0][i];
                    counter ++;
                }
            }
        }
        neutralRatio = NR/counter; //average NR
```
This gives 0 when replacement and silent both zero (sensible).
This gives 0 < Double < Double.infinity when both > 0 (sensible).
This gives 0 when silent > 0 but replacement == 0 (dubious - *exactly* zero..? - but OK).
This gives Double.Infinity when replacement > 0 but silent ==0 (hmm...).

These can be handled any old way easily - but need to decide how...?

**Comment by lonelyjoeparker** [comment]
*Forget this bit - Oli just explained that NR should be taken by aggregating counts across timepoints then taking the average*...

---
Also - in the existing implementation it looks as if neutral ratio is averaged over timepoints where it is estimated (see below). Is this correct?

*(from HCV/p_53, multiple timepoints, 3 replicates)*
```
./HCV_data/main_HCVpacbio_filelist.edited_indivNR
8
0: ./HCV_data/sub_053/FP7_05302_0.3644.fasta : 1680 : 782 neutralRatio:NaN
1: ./HCV_data/sub_053/FP7_05303_0.6137.fasta : 1680 : 909 neutralRatio:NaN
2: ./HCV_data/sub_053/FP7_05304_0.8438.fasta : 1680 : 728 neutralRatio:NaN
3: ./HCV_data/sub_053/FP7_05305_1.3699.fasta : 1680 : 694 neutralRatio:1.075268817204301
4: ./HCV_data/sub_053/FP7_05306_1.7836.fasta : 1680 : 512 neutralRatio:0.5045045045045045
5: ./HCV_data/sub_053/FP7_05307_3.8986.fasta : 1680 : 536 neutralRatio:NaN
6: ./HCV_data/sub_053/FP7_05308_6.8429.fasta : 1680 : 555 neutralRatio:NaN
7: ./HCV_data/sub_053/FP7_05309_7.6849.fasta : 1680 : 513 neutralRatio:0.0
>p_53: r_m = 3.335988023952096, s_m = 4.676011976047905 average_nr = 0.7134258939113375
```

**Comment by lonelyjoeparker** [comment]
After talking with Oli his opinion is that a NaN ratio is the correct behaviour in the sense that an absence of information to calculate the ratio should raise a warning or exception, flagging a possibly invalid analysis to the user.

**Comment by jnarag** [comment]
Hi Joe, 

Yes, I also agree with this conclusion. If you are estimating NaN for your neutral ratio, you shouldn’t be using our method to calculate adaptive substitution rates. 

I have a couple of deadlines today/tomorrow but I will try to answer your query about bootstrapping by tomorrow, if not Thursday. Hope I am not holding you up. 

Jayna

**Comment by jnarag** [comment]
This is correct - the main idea is that you may not necessarily observe mutations at all time points (especially during earlier time points as your population has not significantly diverged), but averaged across should give you a representative neutral ratio. It’s the approach taken in Bhatt et al (2011) - flu paper in MBE. 

Jayna

**Comment by lonelyjoeparker** [comment]
No worries, I'm going to close this as I can move on with the NR stuff now - bootstrapping can wait.
